use std::path::Path;

pub(crate) const RESOLV_CONF_PATH: &str = "/etc/resolv.conf";
pub(crate) const OPENRESOLV_SIGNATURE: &str = "# Generated by resolvconf";

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub(crate) enum ResolvConfState {
    Missing,
    Unmanaged,
    OpenResolv,
    Foreign,
}

pub(crate) fn classify(path: &Path) -> ResolvConfState {
    let link = match std::fs::symlink_metadata(path) {
        Ok(metadata) if metadata.file_type().is_symlink() => std::fs::read_link(path).ok(),
        Ok(_) => None,
        Err(error) if error.kind() == std::io::ErrorKind::NotFound => {
            return ResolvConfState::Missing;
        }
        Err(_) => return ResolvConfState::Foreign,
    };
    let target_is_file = match std::fs::metadata(path) {
        Ok(metadata) => metadata.is_file(),
        Err(error) if error.kind() == std::io::ErrorKind::NotFound => {
            return ResolvConfState::Foreign;
        }
        Err(_) => return ResolvConfState::Foreign,
    };
    if !target_is_file {
        return ResolvConfState::Foreign;
    }
    let content = match std::fs::read(path) {
        Ok(content) => Some(content),
        Err(error) if error.kind() == std::io::ErrorKind::NotFound => None,
        Err(_) => return ResolvConfState::Foreign,
    };
    classify_parts(link.as_deref(), content.as_deref())
}

pub(crate) fn classify_parts(link: Option<&Path>, content: Option<&[u8]>) -> ResolvConfState {
    if link.is_some() {
        if content.is_some_and(has_openresolv_signature) {
            return ResolvConfState::OpenResolv;
        }
        return ResolvConfState::Foreign;
    }
    let Some(content) = content else {
        return ResolvConfState::Missing;
    };
    if has_openresolv_signature(content) {
        return ResolvConfState::OpenResolv;
    }
    if has_foreign_manager_marker(content) {
        return ResolvConfState::Foreign;
    }
    ResolvConfState::Unmanaged
}

pub(crate) fn has_openresolv_signature(content: &[u8]) -> bool {
    content
        .split(|byte| *byte == b'\n')
        .next()
        .is_some_and(|line| line == OPENRESOLV_SIGNATURE.as_bytes())
}

fn has_foreign_manager_marker(content: &[u8]) -> bool {
    let head = String::from_utf8_lossy(content);
    head.lines().take(5).any(|line| {
        let line = line.to_ascii_lowercase();
        line.contains("generated by")
            || line.contains("created by")
            || line.contains("managed by")
            || line.contains("dhclient")
            || line.contains("dhcpcd")
    })
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::path::PathBuf;

    #[test]
    fn openresolv_requires_its_exact_top_line() {
        assert_eq!(
            classify_parts(
                None,
                Some(b"# Generated by resolvconf\nnameserver 1.1.1.1\n")
            ),
            ResolvConfState::OpenResolv
        );
        assert_eq!(
            classify_parts(None, Some(b"# generated by resolvconf\n")),
            ResolvConfState::Foreign
        );
        assert_eq!(
            classify_parts(None, Some(b"# prefix\n# Generated by resolvconf\n")),
            ResolvConfState::Foreign
        );
    }

    #[test]
    fn foreign_managers_and_unknown_symlinks_are_not_unmanaged() {
        assert_eq!(
            classify_parts(None, Some(b"# Generated by dhclient\n")),
            ResolvConfState::Foreign
        );
        assert_eq!(
            classify_parts(None, Some(b"# Created by dhcpcd\n")),
            ResolvConfState::Foreign
        );
        assert_eq!(
            classify_parts(Some(&PathBuf::from("/run/other/resolv.conf")), None),
            ResolvConfState::Foreign
        );
    }

    #[test]
    fn static_and_missing_files_are_distinct() {
        assert_eq!(
            classify_parts(None, Some(b"nameserver 1.1.1.1\n")),
            ResolvConfState::Unmanaged
        );
        assert_eq!(classify_parts(None, None), ResolvConfState::Missing);
    }
}
