use std::path::Path;
use std::sync::Arc;

use crate::error::{Error, Result};
use crate::platform::linux::network_manager::NetworkManager;
use crate::platform::linux::resolvconf;
use crate::platform::linux::resolved::SystemdResolved;
use crate::platform::unix::detect::{self, ResolvConfState};

const RESOLV_CONF: &str = crate::platform::linux::RESOLV_CONF_PATH;

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
enum ResolvConfOwner {
    SystemdResolved,
    NetworkManager,
    Resolvconf,
    Foreign,
    Unmanaged,
    Missing,
}

fn resolv_conf_owner() -> ResolvConfOwner {
    let path = Path::new(RESOLV_CONF);
    if let Ok(target) = std::fs::read_link(path) {
        let target = target.to_string_lossy().to_ascii_lowercase();
        if target.contains("systemd/resolve") {
            return ResolvConfOwner::SystemdResolved;
        }
        if target.contains("networkmanager") {
            return ResolvConfOwner::NetworkManager;
        }
    }
    if let Ok(bytes) = std::fs::read(path) {
        if detect::has_openresolv_signature(&bytes) {
            return ResolvConfOwner::Resolvconf;
        }
        let head = String::from_utf8_lossy(&bytes);
        for line in head.lines().take(5) {
            let line = line.to_ascii_lowercase();
            if line.contains("generated by networkmanager") {
                return ResolvConfOwner::NetworkManager;
            }
            if line.contains("generated by") && line.contains("resolved") {
                return ResolvConfOwner::SystemdResolved;
            }
        }
    }
    match detect::classify(path) {
        ResolvConfState::OpenResolv => ResolvConfOwner::Resolvconf,
        ResolvConfState::Foreign => ResolvConfOwner::Foreign,
        ResolvConfState::Unmanaged => ResolvConfOwner::Unmanaged,
        ResolvConfState::Missing => ResolvConfOwner::Missing,
    }
}

fn unavailable(component: &str) -> Error {
    Error::BackendUnavailable(format!(
        "/etc/resolv.conf is owned by {component}, but that component is unavailable"
    ))
}

pub(crate) fn select(owner: &str) -> Result<Arc<dyn crate::platform::Backend>> {
    let file_owner = resolv_conf_owner();
    let resolved = SystemdResolved::connect().ok();
    let resolved_mode = resolved.as_ref().and_then(|backend| backend.mode_hint());
    let resolved_owns = resolved.is_some()
        && (resolved_mode.as_deref() == Some("stub")
            || file_owner == ResolvConfOwner::SystemdResolved);
    if resolved_owns && let Some(backend) = resolved {
        return Ok(Arc::new(backend));
    }

    let network_manager = NetworkManager::connect().ok();
    let (nm_mode, nm_rc_manager) = network_manager
        .as_ref()
        .map(NetworkManager::dns_configuration)
        .unwrap_or(("", ""));
    if nm_mode == "systemd-resolved"
        && let Some(backend) = resolved
    {
        return Ok(Arc::new(backend));
    }
    if nm_rc_manager == "resolvconf" {
        let probe = resolvconf::probe().ok_or_else(|| {
            Error::BackendUnavailable(
                "NetworkManager delegates DNS to resolvconf, but its live state directory could not be verified"
                    .to_string(),
            )
        })?;
        return Ok(Arc::new(resolvconf::new(probe, owner)));
    }
    let nm_owns_directly = network_manager.is_some()
        && (file_owner == ResolvConfOwner::NetworkManager
            || nm_mode == "dnsmasq"
            || matches!(nm_rc_manager, "file" | "symlink" | "managed"));
    if nm_owns_directly && let Some(backend) = network_manager {
        return Ok(Arc::new(backend));
    }

    if file_owner == ResolvConfOwner::Resolvconf {
        let probe = resolvconf::probe().ok_or_else(|| {
            Error::BackendUnavailable(
                "openresolv owns /etc/resolv.conf, but its live state directory could not be verified"
                    .to_string(),
            )
        })?;
        return Ok(Arc::new(resolvconf::new(probe, owner)));
    }
    match file_owner {
        ResolvConfOwner::SystemdResolved => Err(unavailable("systemd-resolved")),
        ResolvConfOwner::NetworkManager => Err(unavailable("NetworkManager")),
        ResolvConfOwner::Foreign => Err(Error::BackendUnavailable(
            "/etc/resolv.conf has an unknown or foreign DNS manager signature".to_string(),
        )),
        ResolvConfOwner::Unmanaged | ResolvConfOwner::Missing => {
            Ok(Arc::new(crate::platform::linux::direct::new()))
        }
        ResolvConfOwner::Resolvconf => unreachable!(),
    }
}
