use std::os::unix::fs::PermissionsExt;
use std::path::{Path, PathBuf};
use std::sync::Arc;

use crate::error::{Error, Result};
use crate::interface::InterfaceInfo;
use crate::normalize::NormalizedConfig;
use crate::ownership::ResourceId;
use crate::platform::linux;
use crate::platform::unix::WatchDirectory;
use crate::platform::unix::detect::{self, ResolvConfState};
use crate::platform::unix::direct::{DirectFileMetadata, DirectPolicy, DirectResolvConf};

struct LinuxDirectPolicy {
    resource: ResourceId,
}

impl LinuxDirectPolicy {
    fn new() -> Self {
        Self {
            resource: ResourceId::new("linux:resolv-conf").expect("valid resource"),
        }
    }
}

impl DirectPolicy for LinuxDirectPolicy {
    fn check_usable(&self, path: &Path) -> Result<()> {
        match detect::classify(path) {
            ResolvConfState::Missing | ResolvConfState::Unmanaged => Ok(()),
            ResolvConfState::OpenResolv => Err(Error::unsupported(
                crate::capability::BackendKind::ResolvConfFile,
                "/etc/resolv.conf is managed by resolvconf",
            )),
            ResolvConfState::Foreign => Err(Error::unsupported(
                crate::capability::BackendKind::ResolvConfFile,
                "/etc/resolv.conf is managed by another DNS configuration system",
            )),
        }
    }

    fn metadata(&self, path: &Path) -> Result<Option<DirectFileMetadata>> {
        match std::fs::metadata(path) {
            Ok(metadata) => Ok(Some(DirectFileMetadata {
                mode: metadata.permissions().mode(),
                owner: None,
                flags: None,
                links: None,
                modified: None,
            })),
            Err(error) if error.kind() == std::io::ErrorKind::NotFound => Ok(None),
            Err(error) => Err(error.into()),
        }
    }

    fn write(
        &self,
        path: &Path,
        content: &[u8],
        mode: Option<u32>,
        _metadata: Option<&DirectFileMetadata>,
        _restore_modified_time: bool,
    ) -> Result<()> {
        let mut file = atomic_write_file::AtomicWriteFile::open(path)?;
        std::io::Write::write_all(&mut file, content)?;
        if let Some(mode) = mode {
            file.as_file()
                .set_permissions(std::fs::Permissions::from_mode(mode))?;
        }
        file.sync_all()?;
        file.commit()?;
        Ok(())
    }

    fn metadata_equivalent(
        &self,
        left: Option<&DirectFileMetadata>,
        right: Option<&DirectFileMetadata>,
    ) -> bool {
        left.zip(right)
            .is_none_or(|(left, right)| left.mode == right.mode)
    }

    fn mutation_metadata_preserved(
        &self,
        before: Option<&DirectFileMetadata>,
        after: Option<&DirectFileMetadata>,
    ) -> bool {
        before
            .zip(after)
            .is_none_or(|(before, after)| before.mode == after.mode)
    }

    fn list_interfaces(&self) -> Result<Vec<InterfaceInfo>> {
        linux::list_interfaces()
    }

    fn watch_directory(&self) -> WatchDirectory {
        linux::watch::watch_directories
    }

    fn validate_plan(&self, _plan: &NormalizedConfig) -> Result<()> {
        Ok(())
    }

    fn resource(&self) -> &ResourceId {
        &self.resource
    }
}

pub(crate) fn new() -> DirectResolvConf {
    DirectResolvConf::new(
        PathBuf::from(linux::RESOLV_CONF_PATH),
        Arc::new(LinuxDirectPolicy::new()),
    )
}

#[cfg(test)]
mod tests {
    use super::*;

    fn metadata(mode: u32) -> DirectFileMetadata {
        DirectFileMetadata {
            mode,
            owner: None,
            flags: None,
            links: None,
            modified: None,
        }
    }

    #[test]
    fn direct_policy_rejects_foreign_generated_files() {
        let directory = tempfile::tempdir().unwrap();
        let path = directory.path().join("resolv.conf");
        std::fs::write(&path, b"# Generated by NetworkManager\n").unwrap();
        assert!(LinuxDirectPolicy::new().check_usable(&path).is_err());
    }

    #[test]
    fn direct_policy_applies_captured_mode_to_replacement() {
        let directory = tempfile::tempdir().unwrap();
        let path = directory.path().join("resolv.conf");
        let policy = LinuxDirectPolicy::new();
        std::fs::write(&path, b"nameserver 192.0.2.1\n").unwrap();
        std::fs::set_permissions(&path, std::fs::Permissions::from_mode(0o100640)).unwrap();
        let captured = policy.metadata(&path).unwrap().unwrap();
        std::fs::set_permissions(&path, std::fs::Permissions::from_mode(0o100600)).unwrap();

        policy
            .write(
                &path,
                b"nameserver 192.0.2.2\n",
                Some(captured.mode),
                Some(&captured),
                false,
            )
            .unwrap();

        let observed_mode = std::fs::metadata(&path).unwrap().permissions().mode();
        assert_eq!(observed_mode & 0o7777, 0o640);
    }

    #[test]
    fn direct_policy_metadata_equivalent_compares_modes_with_wildcards() {
        let policy = LinuxDirectPolicy::new();
        let left = metadata(0o100644);
        let same = metadata(0o100644);
        let different = metadata(0o100600);

        assert!(policy.metadata_equivalent(Some(&left), Some(&same)));
        assert!(!policy.metadata_equivalent(Some(&left), Some(&different)));
        assert!(policy.metadata_equivalent(None, None));
        assert!(policy.metadata_equivalent(None, Some(&different)));
        assert!(policy.metadata_equivalent(Some(&different), None));
    }

    #[test]
    fn direct_policy_mutation_metadata_preserved_compares_modes_with_wildcards() {
        let policy = LinuxDirectPolicy::new();
        let before = metadata(0o100644);
        let same = metadata(0o100644);
        let different = metadata(0o100600);

        assert!(policy.mutation_metadata_preserved(Some(&before), Some(&same)));
        assert!(!policy.mutation_metadata_preserved(Some(&before), Some(&different)));
        assert!(policy.mutation_metadata_preserved(None, None));
        assert!(policy.mutation_metadata_preserved(None, Some(&different)));
        assert!(policy.mutation_metadata_preserved(Some(&different), None));
    }
}
