use std::os::unix::fs::PermissionsExt;
use std::path::{Path, PathBuf};
use std::sync::Arc;

use crate::error::{Error, Result};
use crate::interface::InterfaceInfo;
use crate::normalize::NormalizedConfig;
use crate::ownership::ResourceId;
use crate::platform::linux;
use crate::platform::unix::WatchDirectory;
use crate::platform::unix::detect::{self, ResolvConfState};
use crate::platform::unix::direct::{DirectFileMetadata, DirectPolicy, DirectResolvConf};

struct LinuxDirectPolicy {
    resource: ResourceId,
}

impl LinuxDirectPolicy {
    fn new() -> Self {
        Self {
            resource: ResourceId::new("linux:resolv-conf").expect("valid resource"),
        }
    }
}

impl DirectPolicy for LinuxDirectPolicy {
    fn check_usable(&self, path: &Path) -> Result<()> {
        match detect::classify(path) {
            ResolvConfState::Missing | ResolvConfState::Unmanaged => Ok(()),
            ResolvConfState::OpenResolv => Err(Error::unsupported(
                crate::capability::BackendKind::ResolvConfFile,
                "/etc/resolv.conf is managed by resolvconf",
            )),
            ResolvConfState::Foreign => Err(Error::unsupported(
                crate::capability::BackendKind::ResolvConfFile,
                "/etc/resolv.conf is managed by another DNS configuration system",
            )),
        }
    }

    fn metadata(&self, path: &Path) -> Result<Option<DirectFileMetadata>> {
        match std::fs::metadata(path) {
            Ok(metadata) => Ok(Some(DirectFileMetadata {
                mode: metadata.permissions().mode(),
                owner: None,
                flags: None,
                links: None,
                modified: None,
            })),
            Err(error) if error.kind() == std::io::ErrorKind::NotFound => Ok(None),
            Err(error) => Err(error.into()),
        }
    }

    fn write(
        &self,
        path: &Path,
        content: &[u8],
        mode: Option<u32>,
        _metadata: Option<&DirectFileMetadata>,
        _restore_modified_time: bool,
    ) -> Result<()> {
        let mut file = atomic_write_file::AtomicWriteFile::open(path)?;
        std::io::Write::write_all(&mut file, content)?;
        file.sync_all()?;
        file.commit()?;
        if let Some(mode) = mode {
            std::fs::set_permissions(path, std::fs::Permissions::from_mode(mode))?;
        }
        Ok(())
    }

    fn metadata_equivalent(
        &self,
        _left: Option<&DirectFileMetadata>,
        _right: Option<&DirectFileMetadata>,
    ) -> bool {
        true
    }

    fn mutation_metadata_preserved(
        &self,
        _before: Option<&DirectFileMetadata>,
        _after: Option<&DirectFileMetadata>,
    ) -> bool {
        true
    }

    fn list_interfaces(&self) -> Result<Vec<InterfaceInfo>> {
        linux::list_interfaces()
    }

    fn watch_directory(&self) -> WatchDirectory {
        linux::watch::watch_directories
    }

    fn validate_plan(&self, _plan: &NormalizedConfig) -> Result<()> {
        Ok(())
    }

    fn resource(&self) -> &ResourceId {
        &self.resource
    }
}

pub(crate) fn new() -> DirectResolvConf {
    DirectResolvConf::new(
        PathBuf::from(linux::RESOLV_CONF_PATH),
        Arc::new(LinuxDirectPolicy::new()),
    )
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn direct_policy_rejects_foreign_generated_files() {
        let directory = tempfile::tempdir().unwrap();
        let path = directory.path().join("resolv.conf");
        std::fs::write(&path, b"# Generated by NetworkManager\n").unwrap();
        assert!(LinuxDirectPolicy::new().check_usable(&path).is_err());
    }
}
